project:
  type: website

website:
  title: "Simple Brand Example"
  navbar:
    title: "dieghernan"
    tools:
    - icon: home
      href: https://dieghernan.github.io
    - icon: github
      href: https://github.com/dieghernan/
    search: true
    right:
    - text: "Quarto Features"
      href: quarto-features.html
    - text: "About"
      href: about.html

  favicon: ./assets/favicon.png
  page-footer:
    left: "This is a test footer"
    right: >
      Visit <a href="https://posit-dev.github.io/brand-yml/">brand-yml</a> for
      more info.

format:
  html:
    css: styles.css
    respect-user-color-scheme: true
    toc: true
    highlight-style:
      light: arrow
      dark: dracula

editor: visual

brand:
  light: light_brand.yml
  dark: dark_brand.yml
